spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trucks
    username: springstudent
    password: springstudent
  
  jpa:
    hibernate:
      ddl-auto: update # This setting will create and drop tables on startup
    show-sql: true # Set to true if you want to see SQL queries in the console
   
      
server:
  port: 8081
  
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
    filter:
      order: 10
